version: "3.2"
services:
  mydepthchartapi:
    image: myapi
    ports:
        - 5000:80    
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

networks:
  default:
    name: mydepthchartapi